3. django/doc-tutorial/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

3. django/doc-tutorial/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name = 'results'),
    path('<int:questionId>/vote/', views.vote, name = 'vote'),
]

3. django/doc-tutorial/mysite/polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime

class Question(models.Model):
    questionText = models.CharField(max_length = 200)
    pubDate = models.DateTimeField('date published')

    def __str__(self):
        # By default, Django displays the str() of each object .
        return self.questionText

    @admin.display(
        boolean = True,
        ordering = 'pubDate',
        description = 'Published recently ?',
    )
    def wasPublishedRecently(self):
        # return self.pubDate >= timezone.now() - datetime.timedelta(days = 1)
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pubDate <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    ChoiceText = models.CharField(max_length = 200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choiceText

3. django/doc-tutorial/mysite/polls/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
from django.views import generic
from django.utils import timezone

# def index(request):
    # latestQuestionList = Question.objects.order_by('-pubDate')[:5]
    # # Means get the first five objects order by their pub date ( descending ) . ( and pub date without - means asscending . ) 
    # context = {
        # 'latestQuestionList' : latestQuestionList,
    # }
    # return render(request, 'polls/index.html', context)

# def detail(request, questionId):
    # question = get_object_or_404(Question, pk = questionId)
    # context = {
        # 'question' : question,
    # }
    # return render(request, 'polls/detail.html', context)

# def results(request, questionId):
    # question = get_object_or_404(Question, pk = questionId)
    # return render(request, 'polls/results.html', {'question' : question,})

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latestQuestionList'
    
    def get_queryset(self):
        # Return the last five published questions (not including those set to be
        # published in the future).
        return Question.objects.filter(pubDate__lte = timezone.now()).order_by('-pubDate')[:5]
        # '__lte =' means less or equal than and '__gte =' means greater or equal than 

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        # Excludes any questions that aren't published yet.
        return Question.objects.filter(pubDate__lte = timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, questionId):
    # We need to avoid race conditions using F()
    question = get_object_or_404(Question, pk = questionId)
    try:
        selectedChoice = question.choiceSet.get(pk = request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        context = {
            'question' : question,
            'errorMessage' : 'You did not select a choice .',
        }
        return render(request, 'polls/detail.html', context)
    else:
        selectedChoice.votes += 1
        selectedChoice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args = (question.id,)))
        

3. django/doc-tutorial/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Django</title>
	</head>
	<body>
		<h1>
			{{ question.questionText }}
		</h1>
		{% if error_message %}
			<p>
				<strong>
					{{error_message}}
				</strong>
			</p>
		{% endif %}
		<form action="{% urls 'polls:vote' question.id %}" method = "post">
			{% csrf_token %}
			{% for choice in question.choiceSet.all %}
				<input type = 'radio' name = 'choice' id = 'choice{{ forloop.counter }}' value = '{{ choice.id }}'>
				<label for = 'choice{{ forloop.counter }}'>
					{{choice.choiceText}}
				</label>
				<br>
			{% endfor %}
			<input type = "submit" value = "Vote">
		</form>
	</body>
</html>

3. django/doc-tutorial/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<title>Django</title>
		<link rel = 'stylesheet' type = 'text/css' href = '{% static "polls/style.css" %}'>
		<!-- The static template tag generates the absolute URL of static files. -->
	</head>
	<body>
		{% if lastestQuestionList %}
			<ul>
				{% for question in latestQuestionList %}
					<li>
						<a href="{% url 'polls:detail' question.id %}">{{question.questionText}}</a>
					</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available .</p>
		{% endif %}
	</body>
</html>

3. django/doc-tutorial/mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Django</title>
	</head>
	
	<body>
		<h1>
			{{question.questionText}}
		</h1>
		
		<ul>
			{% for choice in question.choiceSet.all %}
				<li>
					{{ choice.choiceText }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
					<!-- We use the pluralize filter to change the suffix of a word. If a plural suffix isn’t specified pluralize defaults to ’s’.-->
				</li>
			{% endfor %}
		</ul>
		
		<a href="{% url 'polls:detail' question.id %}">
			Vote again ?  
		</a>
	</body>
</html>